### ISSUE TITLE
 The plugin doesn't work on Mohist.

### ISSUE THREAD

**Issue by zoe-may** [BX-Team/RealWorldSync#25]
When I tried to use this plugin on Mohist, it threw the following error and did not run properly.
`[20:31:24 错误]: Error occurred while enabling RealWorldSync v1.1.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.Server.getMinecraftVersion()'
	at gq.bxteam.realworldsync.RealWorldSync.checkForUpdates(RealWorldSync.java:116) ~[?:?]
	at gq.bxteam.realworldsync.RealWorldSync.onEnable(RealWorldSync.java:41) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.2.20-universal.jar%23523!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.2.20-universal.jar%23523!/:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.20-universal.jar%23523!/:?]
	at com.rylinaux.plugman.util.BukkitPluginUtil.load(BukkitPluginUtil.java:428) ~[?:?]
	at com.rylinaux.plugman.util.BukkitPluginUtil.load(BukkitPluginUtil.java:385) ~[?:?]
	at com.rylinaux.plugman.util.BukkitPluginUtil.reload(BukkitPluginUtil.java:500) ~[?:?]
	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:125) ~[?:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[forge-1.20.1-47.2.20-universal.jar%23523!/:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147) ~[forge-1.20.1-47.2.20-universal.jar%23523!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:885) ~[forge-1.20.1-47.2.20-universal.jar%23523!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:51) ~[forge-1.20.1-47.2.20-universal.jar%23523!/:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.20.1.jar%23142!/:?]
	at net.minecraft.commands.Commands.m_242674_(Commands.java:318) ~[server-1.20.1-20230612.114412-srg.jar%23518!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_246958_(ServerGamePacketListenerImpl.java:1835) ~[server-1.20.1-20230612.114412-srg.jar%23518!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$10(ServerGamePacketListenerImpl.java:1799) ~[server-1.20.1-20230612.114412-srg.jar%23518!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:67) ~[server-1.20.1-20230612.114412-srg.jar%23518!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23518!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23518!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23518!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1029) ~[server-1.20.1-20230612.114412-srg.jar%23518!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:173) ~[server-1.20.1-20230612.114412-srg.jar%23518!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23518!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1012) ~[server-1.20.1-20230612.114412-srg.jar%23518!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1006) ~[server-1.20.1-20230612.114412-srg.jar%23518!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23518!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:991) ~[server-1.20.1-20230612.114412-srg.jar%23518!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:908) ~[server-1.20.1-20230612.114412-srg.jar%23518!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23518!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[20:31:24 信息]: [RealWorldSync] Disabling RealWorldSync v1.1.1
[20:31:24 信息]: [信息] RealWorldSync: Cancelling all tasks
[20:31:24 信息]: [信息] RealWorldSync: Enabling Minecraft default daylight cycle`

**Comment by NONPLAYT** [comment]
RealWorldSync was made for Spigot and Paper platforms that supports Bukkit API. I didn't planned to make plugin work with Mohist
