### ISSUE TITLE
Time sync doesn't work

### ISSUE THREAD

**Issue by ADAMADA8** [BX-Team/RealWorldSync#4]
When I change the time.enabled parameter to true the console starts writing errors every second.

Error:
[11:25:03 WARN]: [RealWorldSync] Plugin RealWorldSync v1.0.0 generated an exception while executing task 45
java.lang.IllegalStateException: TimeSkipEvent may only be triggered synchronously.
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.setFullTime(CraftWorld.java:868) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.setTime(CraftWorld.java:856) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at gq.bxteam.realworldsync.world.WorldManager$1.run(WorldManager.java:34) ~[RealWorldSync-1.0.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by NONPLAYT** [comment]
Before the release of the plugin, I tested everything - I did not find any errors. I think there is a bug in WorldManager, will look into this now

**Comment by NONPLAYT** [comment]
I think problem resolved for now. New version here: https://github.com/BX-Team/RealWorldSync/releases/tag/v1.0.1

If you see this problem again - re-open this issue

**Comment by ADAMADA8** [comment]
problem solved
